const caseData = [
  {
    title: 'Green Blueprint',
    category: 'Brand Identity Design',
    year: '2026',
    services: 'Identity / Art Direction / Packaging',
    summary: 'An eco-conscious construction brand built around a clear vision for sustainable urban design.',
    challenge: 'The company needed a more confident visual language that could work across digital and physical touchpoints.',
    approach: 'We developed a flexible identity system with sharp typography, a memorable symbol and a disciplined visual rhythm.',
    outcome: 'A cohesive, recognizable identity system that brings Green Blueprint’s sustainable construction vision to life across digital and physical touchpoints.',
    colours: ['#1B4839', '#EBEBEB', '#5CAD8D', '#f5cc00'],
    coverImage: 'assets/thumbs/1-green-blueprint-cover-7.jpg',
    galleryImages: [
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%201.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%201.2.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%202.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%203.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%204.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%205.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%206.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%206.2.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%207%20-%20Copy.jpg',
      'assets/Brand%20Identitities/1_Green%20Blueprint/Cover%208.jpg'
    ]
  },
  {
    title: 'Design Eigen',
    category: 'Brand Identity Design',
    year: '2026',
    services: 'Identity / Positioning / Direction',
    summary: 'An identity refresh designed to sharpen the brand story and improve recognition across channels.',
    challenge: 'The business had strong fundamentals but an outdated system that no longer reflected the level of ambition behind it.',
    approach: 'We simplified the visual language, refined the positioning and built a more consistent brand system from the inside out.',
    outcome: 'A cleaner and more premium identity that creates stronger recall and better internal alignment.',
    colours: ['#162daf', '#f7f7f5', '#f5cc00', '#000985'],
    coverImage: 'assets/thumbs/2-design-eigen-imgi-157-c7b3d4219180769-67b0aff187b1c.jpg',
    galleryImages: [
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_200_f1f03a219180769.67ada23ebe1ae.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_201_4a6fc4219180769.67ada43c328d1.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_202_9c26c3219180769.67ada43c31bdc.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_203_0ff659219180769.67ada43c335f3.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_204_b3790b219180769.67ada43c32396.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_205_0ce546219180769.67ada43c32e22.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_206_f968cf219180769.67ada43c313fb.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_207_14d98e219180769.67ada43c30ba9.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/imgi_209_9414ab219180769.67b0aff187247.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/ID%20Card.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/psd%20copy.jpg',
      'assets/Brand%20Identitities/2_Design%20Eigen/Tshirt%20Mockup.jpg'
    ]
  },
  {
    title: 'Bitefort',
    category: 'Brand Identity Design',
    year: '2026',
    services: 'Art Direction / Identity / Messaging',
    summary: 'A confident identity and digital direction for a privacy-first cookie management platform.',
    challenge: 'Bitefort needed a distinctive brand system that could make complex privacy and compliance feel clear, credible and approachable.',
    approach: 'We built a dark, high-contrast visual language around the Bitefort shield and cookie motif, extending it across campaigns, digital touchpoints and branded merchandise.',
    outcome: 'A memorable purple identity that makes trust, privacy and effortless cookie management feel immediate across every touchpoint.',
    colours: ['#21003F', '#F7F4F1', '#6B2FB3', '#0D0616'],
    coverImage: 'assets/thumbs/3-bitefort-1.jpg',
    galleryImages: [
      'assets/Brand%20Identitities/3_Bitefort/2.jpg',
      'assets/Brand%20Identitities/3_Bitefort/3.jpg',
      'assets/Brand%20Identitities/3_Bitefort/4.jpg',
      'assets/Brand%20Identitities/3_Bitefort/5.jpg',
      'assets/Brand%20Identitities/3_Bitefort/6.jpg',
      'assets/Brand%20Identitities/3_Bitefort/7.jpg',
      'assets/Brand%20Identitities/3_Bitefort/8.jpg'
    ]
  },
  {
    title: 'LinkRithm',
    category: 'Brand Identity Design',
    year: '2026',
    services: 'Identity / Packaging / Positioning',
    summary: 'A connected brand identity system built for engineering teams, technical knowledge and digital collaboration.',
    challenge: 'LinkRithm needed a distinctive visual system that could make complex technical relationships feel clear, connected and human.',
    approach: 'We developed a modular identity around linked forms, a deep navy foundation and a violet gradient accent that moves naturally across digital and physical applications.',
    outcome: 'A confident technology brand that gives engineering knowledge a memorable visual rhythm across products, spaces and culture.',
    colours: ['#07112F', '#F7F8FC', '#8B5CF6', '#101A3D'],
    coverImage: 'assets/thumbs/4-linkrithm-linkrithm-cover.jpg',
    galleryImages: [
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-01.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-02.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-03.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-04.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-05.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-06.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-07.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-08.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-09.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-10.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-11.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-12.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-13.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-14.jpg',
      'assets/Brand%20Identitities/4_Linkrithm/linkrithm-gallery-15.jpg'
    ]
  },
  {
    title: 'ShorteeMe',
    category: 'Social Media Design',
    year: '2026',
    services: 'Campaign System / Content Direction',
    summary: 'A bright, human social campaign system helping ShorteeMe make financing feel clear, accessible and full of possibility.',
    challenge: 'ShorteeMe needed a consistent content system that could communicate funding opportunities while keeping people and optimism at the centre.',
    approach: 'We created a flexible campaign language built from bold blue fields, energetic orange accents, expressive headlines and real human stories.',
    outcome: 'A recognizable social presence that makes ShorteeMe’s message easy to understand, share and remember across every campaign format.',
    colours: ['#0057B8', '#F7F7F5', '#FF9700', '#003B7A'],
    coverImage: 'assets/thumbs/1-shorteeme-make-something-amazing-1.jpg',
    galleryImages: [
      'assets/Social%20Media/1_ShorteeMe/Extend%20your%20reach%20today%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Did%20you%20know,%20raise%20money%20for%20what%20matters%20copy%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Fund%20your%20student%20career%20abroad%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Get%20an%20instant%20loan%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Get%20your%20support%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Raise%20money%20for%20free%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Put%20a%20smile%20on%20someone%27s%20face%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Make%20life%20better%20for%20every%20student%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Join%20our%20affiliate%20program%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Come%20get%20funds%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Become%20an%20investor%20today%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Free%20fundraising%20no%20platform%20fee%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Start%20your%20fund%20raising%20campaign%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Your%20Number%201',
      'assets/Social%20Media/1_ShorteeMe/We%20rise%20by%20lifting%20others%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Helping%20each%20other%20can%20make%20the%20world%20better%201.jpg',
      'assets/Social%20Media/1_ShorteeMe/Join%20your%20hand%20with%20us%201.jpg'
    ]
  },
  {
    title: 'Kymela 2026',
    category: 'Social Media Design',
    year: '2026',
    services: 'Social Content / Campaign / Art Direction',
    summary: 'A content system designed to make the brand feel active, intentional and easy to recognize.',
    challenge: 'The brand had strong messages but inconsistent creative execution across channels.',
    approach: 'We built a clear visual format across several campaign stories, each built to feel consistent without becoming repetitive.',
    outcome: 'A social set that improved recognition, helped the team move faster and supported story clarity.',
    colours: ['#2A363B', '#E8D5B5', '#99B898', '#E84A5F'],
    coverImage: 'assets/thumbs/kymela-cover.jpg',
    galleryImages: [
      'assets/Social%20Media/Kymela/img1.jpg',
      'assets/Social%20Media/Kymela/img2.jpg',
      'assets/Social%20Media/Kymela/img3.jpg'
    ]
  },
  {
    title: 'PDOCA',
    category: 'Social Media Design',
    year: '2026',
    services: 'Campaign Art / Social Stories',
    summary: 'A bold campaign identity for PDOCA’s coaching academy, built to create consistent brand presence across multiple formats.',
    challenge: 'The brand needed a clearer, more premium visual rhythm across posts, stories and supporting assets.',
    approach: 'We designed a flexible template system with distinctive crop language, bold type and consistent campaign framing.',
    outcome: 'A consistent media system with stronger visual recall and clearer campaign storytelling.',
    colours: ['#0C0CB4', '#FCFCFC', '#FDCF09', '#0507B0'],
    coverImage: 'assets/thumbs/3-pdoca-layer-5.jpg',
    galleryImages: [
      'assets/Social%20Media/3_PDOCA/RML%20-%20Dealing%20copy%201.jpg',
      'assets/Social%20Media/3_PDOCA/WhatsApp%20Image%202025-02-08%20at%201.27.27%20PM%20(2).jpg',
      'assets/Social%20Media/3_PDOCA/WhatsApp%20Image%202025-02-08%20at%201.27.28%20PM%20-%20Copy.jpg',
      'assets/Social%20Media/3_PDOCA/WhatsApp%20Image%202025-02-08%20at%201.27.28%20PM.jpg',
      'assets/Social%20Media/3_PDOCA/PDOCA%20_June_V2.jpg',
      'assets/Social%20Media/3_PDOCA/August.jpg',
      'assets/Social%20Media/3_PDOCA/September.jpg',
      'assets/Social%20Media/3_PDOCA/October.jpg'
    ]
  },
  {
    title: 'Dress Doctor',
    category: 'Social Media Design',
    year: '2026',
    services: 'Campaign Art / Social Stories',
    summary: 'A bright, service-led campaign system for Dress Doctor Laundry, built to make free pickup and promo offers read at a glance.',
    challenge: 'A growing laundry brand needed its services, promos and booking flow to read instantly across busy social feeds.',
    approach: 'We built a bold, reusable campaign language around cyan panels, orange call-to-actions, playful headlines and clean offer layouts.',
    outcome: 'A recognizable social presence with clearer offers, stronger recall and a consistent publishing rhythm.',
    colours: ['#FF6801', '#162336', '#0CE4FC', '#162336'],
    coverImage: 'assets/thumbs/4-dress-doctor-book-pickup-dd.jpg',
    galleryImages: [
      'assets/Social%20Media/4_Dress%20Doctor/Dress%20Doctor%201.jpg',
      'assets/Social%20Media/4_Dress%20Doctor/Wash%20in%20Bulk.jpg',
      'assets/Social%20Media/4_Dress%20Doctor/BOOK%20PICKUP_DD%20-%20Copy.jpg'
    ]
  },
  {
    title: 'GCE Study App',
    category: 'Social Media Design',
    year: '2026',
    services: 'Campaign Art / Product Promotion',
    summary: 'A fresh, energetic campaign identity introducing the GCE Study App to Cameroonian students.',
    challenge: 'A new edtech brand needed to explain its features quickly and feel trustworthy to students and parents.',
    approach: 'We designed a bold green campaign language with playful type, clear feature call-outs and product mockups.',
    outcome: 'A recognizable launch presence with clearer feature storytelling and stronger engagement across socials.',
    colours: ['#016B29', '#FCFCFC', '#00F4A6', '#004F39'],
    coverImage: 'assets/thumbs/6-gce-study-app-3.jpg',
    galleryImages: [
      'assets/Social%20Media/6_GCE%20Study%20App/2.jpg',
      'assets/Social%20Media/6_GCE%20Study%20App/1.jpg',
      'assets/Social%20Media/6_GCE%20Study%20App/3.2.jpg',
      'assets/Social%20Media/6_GCE%20Study%20App/3%20-%20Copy.jpg'
    ]
  },
  {
    title: 'Proxima Exchange',
    category: 'UI Design',
    year: '2026',
    services: 'Website UI / Interaction Design / 3D / Front-end Build',
    summary: 'A premium website and interface for a crypto and forex trading platform, built directly from the Proxima identity.',
    challenge: 'Trading platforms often feel cold, cluttered and untrustworthy. Proxima needed one calm, credible interface that handles crypto and forex side by side and carries its royal blue, gold and white system into every interaction.',
    approach: 'We turned the logo into the interface: its three colours drive the palette, and the mark itself is rebuilt as a layered 3D object. Bricolage Grotesque, Onest and Geist Mono give a premium but readable rhythm.',
    outcome: 'A fast, responsive website that feels premium and trustworthy, with a live trading terminal, a unified markets view and a clear path from sign-up to first trade. Concept project; figures shown are illustrative.',
    colours: ['#000081', '#ffffff', '#1C39BB', '#FFC000'],
    coverImage: 'assets/thumbs/proxima-exchange-cover.jpg',
    galleryImages: [
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-01-cover.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-02-showcase.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-03-hero.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-04-mobile.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-05-security-3d.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-06-markets.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-07-platform.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-08-fees.jpg',
      'assets/UI%20Design/1_Proxima%20Exchange/proxima-09-brand-board.jpg'
    ]
  },
  {
    title: 'Afa\'a Pay',
    category: 'UI Design',
    year: '2026',
    services: 'Brand Identity / Fintech Website / Dashboard UI / Product Build',
    summary: 'A brand identity, fintech website and working escrow platform for a modern African payment network, built around one promise: building trust into every transaction.',
    challenge: 'Informal commerce across Africa runs on "trust me": buyers pay strangers up front, sellers chase invoices, and disputes have no referee. A payment brand here has to feel safe before it says anything else.',
    approach: 'We built the identity on one idea: two sides meeting at a verified point. The logo is an open A whose strokes converge on a green dot, the same dot that becomes the apostrophe in the wordmark.',
    outcome: 'A complete brand and product system, from logo to ledger: a website that explains escrow in one scroll, and a platform you can sign in to and try as buyer, seller or mediator. Concept project; all figures are illustrative.',
    colours: ['#05060A', '#FFFFFF', '#2F5BFF', '#2EE59D'],
    liveUrl: 'afaa-pay/index.html',
    liveLabel: 'Explore the live concept ↗',
    coverImage: 'assets/thumbs/afaa-pay-cover.jpg',
    galleryImages: [
      'assets/UI%20Design/2_Afaa%20Pay/afaa-01-cover.jpg',
      'assets/UI%20Design/2_Afaa%20Pay/afaa-02-logo.jpg',
      'assets/UI%20Design/2_Afaa%20Pay/afaa-03-colour-type.jpg',
      'assets/UI%20Design/2_Afaa%20Pay/afaa-04-website.jpg',
      'assets/UI%20Design/2_Afaa%20Pay/afaa-05-platform.jpg',
      'assets/UI%20Design/2_Afaa%20Pay/afaa-06-mobile.jpg',
      'assets/UI%20Design/2_Afaa%20Pay/afaa-07-system.jpg',
      'assets/UI%20Design/2_Afaa%20Pay/afaa-08-voice.jpg'
    ]
  },
  {
    title: 'Book Cover Design',
    category: 'Packaging',
    year: '2026',
    services: 'Book Design / Art Direction / Print',
    summary: 'A premium book cover system built to make the title feel authoritative, desirable and impossible to shelve away.',
    challenge: 'The book needed a cover that could carry its message with weight and elegance across print and digital listings.',
    approach: 'We explored bold typographic structures, gold foil accents and disciplined mockup rounds from prototype to final press.',
    outcome: 'A striking black-and-gold cover family that reads powerfully at thumbnail size and feels premium in hand.',
    colours: ['#141414', '#F5F1E6', '#C9A24B', '#8B6B2A'],
    coverImage: 'assets/thumbs/1-book-cover-design-book-cover-mockup-3-1-1.jpg',
    galleryImages: [
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20mockup%203.1%201%20-%20Copy.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20mockup%204%201.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20mockup%204.1%201.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20mockup%205.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20Prototype%201%201.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20Prototype%202%201.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20mockup%201%201.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20mockup%202%201.jpg',
      'assets/Packaging%20Design/1_Book%20Cover%20Design/Book%20Cover%20mockup%203%201.jpg'
    ]
  },
  {
    title: 'JoJo Foods',
    category: 'Packaging',
    year: '2026',
    services: 'Packaging Design / Logo & Lettering / Mockups',
    summary: 'Retro-bright potato chip packaging built around a cream roundel mark, a red and orange sunburst and a clear window that lets the chips do the selling.',
    challenge: 'The snack aisle is loud. JoJo Foods needed a pouch that reads from across the shop, feels friendly rather than corporate, and still shows off the product inside.',
    approach: 'We put the JoJo Foods wordmark on a cream roundel so it holds its own against a high-energy red and orange sunburst. A chunky retro script carries "Crispy Snack" and the "Potato Chip" descriptor with easy recall.',
    outcome: 'A bold, shelf-ready pouch with one clear focal point, a warm colour palette that suits the product and lettering that stays legible at a glance.',
    colours: ['#EC2934', '#EBE9E9', '#EE5930', '#FFDF56'],
    coverImage: 'assets/thumbs/jojo-foods-cover.jpg',
    galleryImages: [
      'assets/Packaging%20Design/2_JoJo%20Foods/jojo-01-hero.jpg',
      'assets/Packaging%20Design/2_JoJo%20Foods/jojo-02-pair.jpg',
      'assets/Packaging%20Design/2_JoJo%20Foods/jojo-03-mark.jpg',
      'assets/Packaging%20Design/2_JoJo%20Foods/jojo-04-colour.jpg',
      'assets/Packaging%20Design/2_JoJo%20Foods/jojo-05-detail.jpg'
    ]
  },
  {
    title: 'Proxima Exchange Films',
    category: 'Motion Design',
    year: '2026',
    services: 'Motion Design / 3D / Cinematic Direction / Sound Design',
    summary: 'Two launch films for a crypto and forex trading platform: a cinematic 3D brand film and a precise product film built from the real interface.',
    challenge: 'Proxima Exchange needed to feel trustworthy and premium in a category full of noise, and to show both the emotion of the brand and the real product in motion.',
    approach: 'We built the logo as a layered 3D object and shot it with a virtual camera: rack focus, light rays and lens streaks, a deep blue and gold grade, and a score cut to every hit. A second film translated the same system into product storytelling on the real UI.',
    outcome: 'Two films that work together: a 40-second cinematic hook for campaigns and social, and a 30-second product film for the website and case studies. Concept project; figures shown are illustrative.',
    colours: ['#000081', '#ffffff', '#1C39BB', '#FFC000'],
    coverImage: 'assets/thumbs/proxima-exchange-films-cover.jpg',
    videos: [
      { title: 'Cinematic Film', src: 'assets/Motion%20Design/2_Proxima%20Exchange%20Films/proxima-exchange-cinematic.mp4', poster: 'assets/Motion%20Design/2_Proxima%20Exchange%20Films/poster-cinematic.jpg' },
      { title: 'Product Film', src: 'assets/Motion%20Design/2_Proxima%20Exchange%20Films/proxima-exchange-film.mp4', poster: 'assets/Motion%20Design/2_Proxima%20Exchange%20Films/poster-film.jpg' }
    ],
    galleryImages: [
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-01-cinematic.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-02-cinematic.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-03-cinematic.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-04-cinematic.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-05-cinematic.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-06-cinematic.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-07-cinematic.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-08-film.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-09-film.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-10-film.jpg',
      'assets/Motion%20Design/2_Proxima%20Exchange%20Films/still-11-film.jpg'
    ]
  },
  {
    title: 'Rovard Studios Brand Film',
    category: 'Motion Design',
    year: '2026',
    services: 'Motion Design / Kinetic Typography / Sound Design',
    summary: 'A 90-second brand film that turns the Rovard identity, services and selected work into one continuous piece of motion.',
    challenge: 'The studio needed a single film that could introduce who Rovard is, what it does and the quality of its work in under two minutes.',
    approach: 'We built every frame from the brand system itself: Syne and Space Grotesk kinetic type, the blue and yellow palette, real project work and a soundtrack composed to cut on every bar.',
    outcome: 'A premium, on-brand film ready for the website, social channels and pitch presentations.',
    colours: ['#000985', '#ffffff', '#162DAF', '#F5CC00'],
    coverImage: 'assets/thumbs/rovard-brand-film-cover.jpg',
    video: 'assets/Motion%20Design/1_Rovard%20Brand%20Film/rovard-brand-film.mp4',
    poster: 'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-01.jpg',
    galleryImages: [
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-02.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-03.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-04.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-05.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-06.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-07.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-08.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-09.jpg',
      'assets/Motion%20Design/1_Rovard%20Brand%20Film/film-10.jpg'
    ]
  },
  {
    title: 'Motion Project 03',
    category: 'Motion Design',
    year: '2026',
    services: 'Campaign Asset / Motion Identity',
    summary: 'A motion-led identity system designed to create tempo and presence without excess.',
    challenge: 'The brand needed motion assets that could feel modern and premium while still matching the broader visual discipline.',
    approach: 'We created a set of modular motion frames and transitions that could be reused across digital campaign moments.',
    outcome: 'A flexible motion toolkit that makes the brand feel more alive across digital channels.',
    colours: ['#162daf', '#f7f7f5', '#f5cc00', '#000985'],
    galleryImages: [
      makeGalleryAsset('Motion Project 03', ['#162daf', '#f7f7f5', '#f5cc00']),
      makeGalleryAsset('Transition', ['#162daf', '#f7f7f5', '#f5cc00']),
      makeGalleryAsset('Teaser', ['#162daf', '#f7f7f5', '#f5cc00']),
      makeGalleryAsset('Campaign', ['#162daf', '#f7f7f5', '#f5cc00']),
      makeGalleryAsset('Final Frame', ['#162daf', '#f7f7f5', '#f5cc00'])
    ]
  }
];
