from playwright.sync_api import sync_playwright
from pw import open_browser, url_for, settle
res = []
def check(name, cond, extra=''):
    res.append((name, bool(cond))); print(('PASS ' if cond else 'FAIL ') + name, extra)

with sync_playwright() as p:
    b = open_browser(p)
    ctx = b.new_context(viewport={'width': 1440, 'height': 900})
    errs = []
    def new(path):
        pg = ctx.new_page(); pg.on('pageerror', lambda e: errs.append(str(e))); pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' else None)
        pg.goto(url_for(path)); settle(pg, scroll=False, wait=400); return pg

    # home
    pg = new('website/index.html')
    pg.click('#menuBtn'); pg.wait_for_timeout(1300)
    check('menu opens', pg.evaluate("document.getElementById('menu').classList.contains('is-open')"))
    check('menu has 10 links', pg.locator('#menu ol a').count() == 10)
    pg.screenshot(path='_shots/i_menu.png')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(900)
    check('menu closes on Esc', not pg.evaluate("document.getElementById('menu').classList.contains('is-open')"))
    pg.evaluate('window.scrollTo(0,0)'); pg.wait_for_timeout(400)
    pg.click('.hero-dots button:nth-child(3)'); pg.wait_for_timeout(500)
    check('hero dot switches slide', 'wren' in pg.inner_text('.hero-cap').lower())
    pg.evaluate("window.scrollTo(0, document.querySelector('#amenList').getBoundingClientRect().top + scrollY - 200)"); pg.wait_for_timeout(500)
    pg.hover('#amenList li:nth-child(4)'); pg.wait_for_timeout(500)
    check('amenity hover activates item', pg.evaluate("document.querySelector('#amenList li:nth-child(4)').classList.contains('is-on')"))
    pg.close()

    # dev detail
    pg = new('website/development.html?d=the-averly')
    check('detail renders averly', 'The Averly' in pg.inner_text('#h-title'))
    check('gallery has 7', pg.locator('#gal figure').count() == 7)
    pg.locator('#gal figure').first.click(); pg.wait_for_timeout(700)
    check('lightbox opens', pg.evaluate("document.querySelector('.lb').classList.contains('is-open')"))
    pg.keyboard.press('ArrowRight'); pg.keyboard.press('Escape'); pg.wait_for_timeout(600)
    pg.click('#planTabs .tab:nth-child(2)'); pg.wait_for_timeout(300)
    check('plan tab switches', 'terrace residence' in pg.inner_text('#planInfo').lower())
    check('plan svg has rooms', pg.locator('#planViewer svg rect').count() > 20)
    pg.locator('#avStack .cell.is-available').first.scroll_into_view_if_needed(); pg.locator('#avStack .cell.is-available').first.click(); pg.wait_for_timeout(400)
    check('unit detail populates', 'request details' in pg.inner_text('#avDetail').lower())
    pg.locator('#avDetail [data-enquire]').click(); pg.wait_for_timeout(700)
    check('enquiry modal opens', pg.evaluate("document.querySelector('.modal').classList.contains('is-open')"))
    pg.screenshot(path='_shots/i_modal.png')
    pg.click('.modal form button[type=submit]'); pg.wait_for_timeout(300)
    check('modal validates empty', pg.locator('.modal .field.err').count() >= 2)
    pg.fill('.modal #eN', 'Alex Morgan'); pg.fill('.modal #eE', 'alex@example.com'); pg.check('.modal input[type=checkbox]')
    pg.click('.modal form button[type=submit]'); pg.wait_for_timeout(500)
    check('modal success state', pg.evaluate("document.querySelector('.modal .success').classList.contains('on')"))
    pg.keyboard.press('Escape'); pg.wait_for_timeout(500)
    pg.fill('#enqForm #n1', 'A'); pg.click('#enqForm button[type=submit]'); pg.wait_for_timeout(200)
    check('inline form validates', pg.locator('#enqForm .field.err').count() >= 1)
    pg.close()

    # availability
    pg = new('website/availability.html?d=halden-house')
    n_all = pg.locator('#avStack .cell:not(.is-dim)').count()
    pg.click('[data-f="beds:3"]'); pg.wait_for_timeout(300)
    n3 = pg.locator('#avStack .cell:not(.is-dim)').count()
    check('beds filter dims cells', 0 < n3 < n_all, f'{n_all}->{n3}')
    pg.click('[data-view="list"]'); pg.wait_for_timeout(300)
    check('list view shows rows', pg.locator('#avTable tr.row').count() == n3, str(pg.locator('#avTable tr.row').count()))
    pg.click('#avTabs .tab:nth-child(3)'); pg.wait_for_timeout(500)
    check('tab switches development', 'Wren' in pg.inner_text('#avHead'))
    pg.click('[data-view="stack"]'); pg.locator('#avStack .cell').first.click(); pg.wait_for_timeout(300)
    pg.screenshot(path='_shots/i_avail.png')
    check('villa unit shows terrace area', 'outdoor' in pg.inner_text('#avDetail').lower())
    pg.close()

    # private viewing flow
    pg = new('website/private-viewing.html?d=quarry-house')
    check('dev preselected from URL', pg.is_checked('#dv-quarry-house'))
    pg.click('#to2'); pg.wait_for_timeout(500)
    pg.click('#to3'); pg.wait_for_timeout(200)
    check('requires date+time', pg.is_visible('#err2'))
    days = pg.locator('#calGrid .day:not([disabled])'); days.nth(3).click(); pg.wait_for_timeout(200)
    pg.locator('#slots .slot:not([disabled])').first.click()
    pg.screenshot(path='_shots/i_cal.png')
    pg.click('#to3'); pg.wait_for_timeout(500)
    check('reaches details step', pg.evaluate("document.getElementById('step3').classList.contains('on')"))
    pg.fill('#pvName', 'Alex Morgan'); pg.fill('#pvEmail', 'alex@example.com'); pg.check('#pvForm input[type=checkbox]')
    pg.click('#pvForm button[type=submit]'); pg.wait_for_timeout(600)
    check('ticket confirmation', 'Quarry House' in pg.inner_text('#tkt'))
    pg.screenshot(path='_shots/i_ticket.png')
    pg.close()

    # residences / neighborhood / contact
    pg = new('website/residences.html')
    pg.click('[data-kind="Villa"]'); pg.wait_for_timeout(300)
    check('villa filter', pg.locator('#resList .rcard').count() == 2, str(pg.locator('#resList .rcard').count()))
    pg.click('[data-scheme="b"]'); pg.wait_for_timeout(300)
    check('scheme toggle', pg.evaluate("document.getElementById('scheme').classList.contains('is-b')"))
    pg.close()
    pg = new('website/neighborhood.html')
    pg.click('#cityTabs .tab:nth-child(3)'); pg.wait_for_timeout(400)
    check('city tab switches', 'Brentwood' in pg.inner_text('#hoodHead'))
    pg.click('#hoodMap .fbtn:nth-child(3)'); pg.wait_for_timeout(300)
    check('poi filter hides items', pg.locator('#hoodMap .poilist li.is-dim').count() > 0)
    pg.close()
    pg = new('website/contact.html')
    pg.click('#cForm button[type=submit]'); pg.wait_for_timeout(200)
    check('contact validates', pg.locator('#cForm .field.err').count() >= 2)
    pg.close()
    b.close()
print('console/page errors:', errs[:5])
print(f'{sum(1 for _,ok in res if ok)}/{len(res)} passed')
