# Six more blog posts, each with its French version side by side (same structure, same order).
# tools/build.py appends them to POSTS; tools/i18n.py gets the English->French pairs from FR_PAIRS().
# Plain advice only: no client names, results or statistics are claimed.
MORE = [
    dict(slug='choosing-brand-colours', cover='kymela-2026', tag='Branding',
         en=dict(title="How to choose colours for your brand",
                 excerpt="Colour is the fastest way people recognize you. Here's how to choose a small set that works.",
                 body=[('p', "People notice colour before they read a single word, so the colours you choose do a lot of quiet work for your brand. The good news is you don't need many."),
                       ('h', "Start with how you want people to feel"),
                       ('p', "Calm, energetic, trustworthy, playful, premium? Pick the feeling first, then look for colours that carry it. Blue often feels steady, yellow feels optimistic, dark tones feel serious. There are no rules, only habits people already have."),
                       ('h', "Keep the set small"),
                       ('ul', ["One main colour that people will remember", "One or two supporting colours", "One neutral for text and backgrounds (often a dark and a light)"]),
                       ('h', "Check the contrast"),
                       ('p', "Text has to be easy to read on its background, on a phone in bright light as well as on a big screen. If two colours are close in brightness, people will struggle to read words placed on them."),
                       ('h', "Write the exact codes down"),
                       ('p', "\"Blue\" turns into ten different blues the moment several people work on your brand. Keep the exact codes (like #162DAF) in one place and use them every time."),
                       ('h', "Test them in the real places"),
                       ('p', "Put your colours on a sign, a business card and a social post before you commit. Colours can look different on screen and in print, so check both.")]),
         fr=dict(title="Comment choisir les couleurs de votre marque",
                 excerpt="La couleur est le moyen le plus rapide de se faire reconnaître. Voici comment choisir un petit ensemble qui fonctionne.",
                 body=[('p', "Les gens remarquent la couleur avant de lire un seul mot, et les couleurs que vous choisissez travaillent donc beaucoup en silence pour votre marque. La bonne nouvelle, c'est qu'il n'en faut pas beaucoup."),
                       ('h', "Commencez par ce que vous voulez faire ressentir"),
                       ('p', "Calme, énergique, fiable, ludique, haut de gamme? Choisissez d'abord l'émotion, puis cherchez les couleurs qui la portent. Le bleu inspire souvent la stabilité, le jaune l'optimisme, les tons sombres le sérieux. Il n'y a pas de règles, seulement des habitudes que les gens ont déjà."),
                       ('h', "Gardez un petit ensemble"),
                       ('ul', ["Une couleur principale dont les gens se souviendront", "Une ou deux couleurs complémentaires", "Un neutre pour le texte et les fonds (souvent un foncé et un clair)"]),
                       ('h', "Vérifiez le contraste"),
                       ('p', "Le texte doit se lire facilement sur son fond, sur un téléphone en plein soleil comme sur un grand écran. Si deux couleurs ont une luminosité proche, les mots placés dessus seront difficiles à lire."),
                       ('h', "Notez les codes exacts"),
                       ('p', "« Bleu » devient dix bleus différents dès que plusieurs personnes travaillent sur votre marque. Gardez les codes exacts (comme #162DAF) à un seul endroit et utilisez-les chaque fois."),
                       ('h', "Testez-les dans les vrais endroits"),
                       ('p', "Mettez vos couleurs sur une enseigne, une carte professionnelle et une publication sociale avant de vous engager. Les couleurs peuvent paraître différentes à l'écran et à l'impression, alors vérifiez les deux.")])),
    dict(slug='choosing-fonts', cover='book-cover-design', tag='Branding',
         en=dict(title="Choosing fonts without overthinking it",
                 excerpt="Two fonts are usually enough. How to pick them and how to use them well.",
                 body=[('p', "Fonts shape how your words sound before anyone reads them. A serious font and a playful font can say the same sentence in very different voices."),
                       ('h', "Use two, at most"),
                       ('p', "One font for headlines and one for text is almost always enough. When a design has four or five fonts, it usually looks busy rather than creative."),
                       ('h', "Match the voice"),
                       ('ul', ["Rounded, friendly shapes feel approachable", "Sharp, narrow shapes feel modern and serious", "Serifs (the small feet on letters) feel established and editorial"]),
                       ('h', "Readability comes first"),
                       ('p', "A beautiful font that's hard to read at a small size will hurt more than it helps. Test your choice at the smallest size you'll use it, such as a phone screen or a line on a label."),
                       ('h', "Check the licence"),
                       ('p', "Some fonts are free for personal use but not for business. Before you commit, confirm you're allowed to use the font for the way you'll use it, including on a website or in print."),
                       ('h', "Be consistent"),
                       ('p', "Once you've chosen, use the same fonts everywhere: your website, documents, social posts and signs. Consistency is what makes a brand feel put together.")]),
         fr=dict(title="Choisir ses polices sans trop y penser",
                 excerpt="Deux polices suffisent généralement. Comment les choisir et bien les utiliser.",
                 body=[('p', "Les polices donnent le ton de vos mots avant même que quelqu'un les lise. Une police sérieuse et une police ludique peuvent dire la même phrase avec des voix très différentes."),
                       ('h', "N'en utilisez que deux, tout au plus"),
                       ('p', "Une police pour les titres et une pour le texte suffisent presque toujours. Quand un design en compte quatre ou cinq, il paraît généralement chargé plutôt que créatif."),
                       ('h', "Accordez-les à votre voix"),
                       ('ul', ["Les formes arrondies et amicales paraissent accessibles", "Les formes nettes et étroites paraissent modernes et sérieuses", "Les empattements (les petits pieds des lettres) paraissent établis et éditoriaux"]),
                       ('h', "La lisibilité d'abord"),
                       ('p', "Une belle police difficile à lire en petit format fait plus de tort que de bien. Testez votre choix à la plus petite taille où vous l'utiliserez, comme un écran de téléphone ou une ligne sur une étiquette."),
                       ('h', "Vérifiez la licence"),
                       ('p', "Certaines polices sont gratuites pour un usage personnel mais pas pour une entreprise. Avant de vous engager, confirmez que vous avez le droit d'utiliser la police comme vous le ferez, y compris sur un site Web ou à l'impression."),
                       ('h', "Soyez cohérent"),
                       ('p', "Une fois votre choix fait, utilisez les mêmes polices partout : site Web, documents, publications sociales et enseignes. La cohérence est ce qui donne à une marque un air soigné.")])),
    dict(slug='how-to-give-design-feedback', cover='pdoca', tag='Working together',
         en=dict(title="How to give feedback on a design",
                 excerpt="Good feedback gets you to the right design faster. A simple way to give it.",
                 body=[('p', "Most people find it hard to say what they don't like about a design, especially when they can't say why. The good news is you don't need design words. You just need to be specific about what you notice."),
                       ('h', "Say what you see and how it feels"),
                       ('p', "\"It feels too serious for our audience\" helps a designer much more than \"I don't like it\". Describe the feeling, not the fix. Let the designer solve it."),
                       ('h', "Start with what's working"),
                       ('p', "Tell us what you do like. It keeps those parts safe while we change the rest."),
                       ('h', "Collect everyone's comments first"),
                       ('p', "When several people are involved, gather their feedback into one message before sending it. Conflicting comments sent one at a time slow everything down."),
                       ('h', "Connect it to the goal"),
                       ('p', "Remind us who the design is for and what it should do. \"Older customers need to read this from a distance\" gives us something real to work with."),
                       ('h', "Point, don't just describe"),
                       ('ul', ["Circle or number the parts you mean on a screenshot", "Send examples of what you have in mind, and what you don't", "Tell us which comments matter most"]),
                       ('p', "A round of feedback with a clear goal will usually get you closer than three rounds of vague ones.")]),
         fr=dict(title="Comment donner des commentaires sur un design",
                 excerpt="De bons commentaires vous mènent plus vite au bon design. Une façon simple de les donner.",
                 body=[('p', "Beaucoup de gens ont du mal à dire ce qu'ils n'aiment pas dans un design, surtout quand ils ne savent pas pourquoi. La bonne nouvelle, c'est que vous n'avez pas besoin des mots du design. Il suffit d'être précis sur ce que vous remarquez."),
                       ('h', "Dites ce que vous voyez et ce que vous ressentez"),
                       ('p', "« Cela paraît trop sérieux pour notre public » aide beaucoup plus un designer que « je n'aime pas ». Décrivez l'impression, pas la solution. Laissez le designer la trouver."),
                       ('h', "Commencez par ce qui fonctionne"),
                       ('p', "Dites-nous ce que vous aimez. Cela protège ces éléments pendant que nous changeons le reste."),
                       ('h', "Regroupez d'abord les commentaires de tout le monde"),
                       ('p', "Quand plusieurs personnes sont concernées, rassemblez leurs commentaires dans un seul message avant de l'envoyer. Des commentaires contradictoires envoyés un à un ralentissent tout."),
                       ('h', "Reliez-les à l'objectif"),
                       ('p', "Rappelez-nous à qui le design s'adresse et ce qu'il doit accomplir. « Les clients plus âgés doivent pouvoir lire ceci de loin » nous donne quelque chose de concret."),
                       ('h', "Montrez du doigt plutôt que de seulement décrire"),
                       ('ul', ["Entourez ou numérotez les parties visées sur une capture d'écran", "Envoyez des exemples de ce que vous avez en tête, et de ce que vous ne voulez pas", "Dites-nous quels commentaires comptent le plus"]),
                       ('p', "Une ronde de commentaires avec un objectif clair vous rapprochera généralement davantage que trois rondes vagues.")])),
    dict(slug='business-cards-people-keep', cover='bitefort', tag='Flyers & print',
         en=dict(title="Business cards people actually keep",
                 excerpt="A card only works if it's still around next week. What makes people hold on to one.",
                 body=[('p', "A business card is small, but it's often the first physical thing someone holds of yours. Here's what helps it stay in a wallet instead of the bin."),
                       ('h', "Put the essentials first"),
                       ('ul', ["Your name and what you do", "One way to reach you that you check every day", "Your website or social handle, if people will use it"]),
                       ('p', "Everything else is optional. A crowded card is hard to read and easy to forget."),
                       ('h', "Make the text big enough"),
                       ('p', "If you have to squint, it's too small. Phone numbers and web addresses should be easy to read at arm's length."),
                       ('h', "Use the back"),
                       ('p', "The back can carry a short line about what you do, a map, or a QR code. Just be sure the QR code is large enough to scan and links to something useful."),
                       ('h', "Think about the paper"),
                       ('p', "Thicker or textured paper feels more considered. Ask your printer for samples before you decide."),
                       ('h', "Match your brand"),
                       ('p', "The card should look like it came from the same place as your website and signs. Use the same colours, fonts and logo.")]),
         fr=dict(title="Des cartes professionnelles que les gens gardent vraiment",
                 excerpt="Une carte ne sert que si on l'a encore la semaine suivante. Ce qui fait qu'on la garde.",
                 body=[('p', "Une carte professionnelle est petite, mais c'est souvent la première chose concrète que quelqu'un reçoit de vous. Voici ce qui l'aide à rester dans un portefeuille plutôt que de finir à la poubelle."),
                       ('h', "Mettez l'essentiel d'abord"),
                       ('ul', ["Votre nom et ce que vous faites", "Une façon de vous joindre que vous consultez chaque jour", "Votre site Web ou votre identifiant social, si les gens s'en serviront"]),
                       ('p', "Tout le reste est facultatif. Une carte surchargée est difficile à lire et facile à oublier."),
                       ('h', "Rendez le texte assez grand"),
                       ('p', "Si vous devez plisser les yeux, c'est trop petit. Les numéros de téléphone et adresses Web doivent se lire facilement à bout de bras."),
                       ('h', "Utilisez le verso"),
                       ('p', "Le verso peut porter une courte phrase sur ce que vous faites, une carte ou un code QR. Assurez-vous seulement que le code QR est assez grand pour être numérisé et mène à quelque chose d'utile."),
                       ('h', "Pensez au papier"),
                       ('p', "Un papier plus épais ou texturé donne une impression plus soignée. Demandez des échantillons à votre imprimeur avant de décider."),
                       ('h', "Accordez-la à votre marque"),
                       ('p', "La carte doit sembler venir du même endroit que votre site Web et vos enseignes. Utilisez les mêmes couleurs, polices et logo.")])),
    dict(slug='preparing-files-for-print', cover='dress-doctor', tag='Flyers & print',
         en=dict(title="Preparing files for print: bleed, size and colour",
                 excerpt="Three small details that decide whether your print job comes back right.",
                 body=[('p', "A design can look perfect on screen and still cause trouble at the printer. Three details prevent most problems."),
                       ('h', "1. Size and bleed"),
                       ('p', "Ask your printer for the exact finished size. Then add bleed, a few millimetres of extra background that runs past the edge, so nothing is left with a white line when the paper is cut."),
                       ('h', "2. Safe area"),
                       ('p', "Keep important words and logos away from the edge, inside a safe margin. Paper moves a little when it's cut, so text too close to the edge can be clipped."),
                       ('h', "3. Colour"),
                       ('p', "Screens mix light and print mixes ink, so colours can shift. Ask your printer which colour setup they want, and request a proof for anything important. Don't expect a bright screen colour to match exactly."),
                       ('h', "Also check"),
                       ('ul', ["Images are sharp enough at the printed size", "Fonts are included or converted, so nothing changes", "The file type your printer asks for (often PDF)"]),
                       ('p', "If you're not sure, send us your printer's requirements and we'll set the files up for you.")]),
         fr=dict(title="Préparer des fichiers pour l'impression : fond perdu, format et couleur",
                 excerpt="Trois petits détails qui déterminent si votre impression revient comme prévu.",
                 body=[('p', "Un design peut paraître parfait à l'écran et causer des problèmes chez l'imprimeur. Trois détails évitent la plupart des ennuis."),
                       ('h', "1. Format et fond perdu"),
                       ('p', "Demandez à votre imprimeur le format fini exact. Ajoutez ensuite un fond perdu, quelques millimètres de fond supplémentaires qui dépassent du bord, pour qu'aucun liséré blanc ne reste quand le papier est coupé."),
                       ('h', "2. Zone de sécurité"),
                       ('p', "Gardez les mots importants et les logos loin du bord, à l'intérieur d'une marge de sécurité. Le papier bouge un peu à la coupe, alors un texte trop près du bord peut être rogné."),
                       ('h', "3. Couleur"),
                       ('p', "Les écrans mélangent la lumière et l'impression mélange l'encre, donc les couleurs peuvent changer. Demandez à votre imprimeur quel profil de couleur il veut, et exigez une épreuve pour tout ce qui est important. Ne comptez pas sur une couleur éclatante d'écran pour qu'elle soit identique."),
                       ('h', "À vérifier aussi"),
                       ('ul', ["Les images sont assez nettes à la taille imprimée", "Les polices sont incluses ou converties, pour que rien ne change", "Le type de fichier demandé par votre imprimeur (souvent PDF)"]),
                       ('p', "Si vous avez un doute, envoyez-nous les exigences de votre imprimeur et nous préparerons les fichiers pour vous.")])),
    dict(slug='designing-an-event-poster', cover='gce-study-app', tag='Flyers & print',
         en=dict(title="Designing a poster for a church or community event",
                 excerpt="People walk past posters quickly. Here's how to make yours worth stopping for.",
                 body=[('p', "Most people see a poster for two or three seconds. In that time, it has to answer three questions: what is it, when is it, and where."),
                       ('h', "Lead with the event"),
                       ('p', "The name of the event should be the biggest thing on the page. Everything else supports it."),
                       ('h', "Put the date and place where they can be found"),
                       ('p', "Write the day, date, time and place clearly, and keep them together. Don't hide them in a corner or in small print."),
                       ('h', "One image, or none"),
                       ('p', "A single strong photo or illustration works better than a collage. If you don't have a good image, bold type on a clean colour can look excellent."),
                       ('h', "Say what to do next"),
                       ('ul', ["Who to call or message", "A website or QR code to learn more", "If it's free, or if people need to register"]),
                       ('h', "Make it work in two sizes"),
                       ('p', "The same message often needs a large poster for a wall and a square image for social media. Ask for both so people see it in every place."),
                       ('p', "Read it once from across the room. If you can't tell what the event is, it needs to be simpler.")]),
         fr=dict(title="Concevoir une affiche pour un événement d'église ou communautaire",
                 excerpt="Les gens passent vite devant les affiches. Voici comment faire que la vôtre vaille un arrêt.",
                 body=[('p', "La plupart des gens regardent une affiche deux ou trois secondes. Pendant ce temps, elle doit répondre à trois questions : de quoi s'agit-il, quand, et où."),
                       ('h', "Mettez l'événement en tête"),
                       ('p', "Le nom de l'événement doit être l'élément le plus grand de la page. Tout le reste le soutient."),
                       ('h', "Placez la date et le lieu là où on les trouve"),
                       ('p', "Écrivez clairement le jour, la date, l'heure et le lieu, et gardez-les ensemble. Ne les cachez pas dans un coin ni en petits caractères."),
                       ('h', "Une image, ou aucune"),
                       ('p', "Une seule photo ou illustration forte fonctionne mieux qu'un collage. Si vous n'avez pas de bonne image, une typographie audacieuse sur une couleur unie peut être excellente."),
                       ('h', "Dites quoi faire ensuite"),
                       ('ul', ["Qui appeler ou à qui écrire", "Un site Web ou un code QR pour en savoir plus", "Si c'est gratuit, ou s'il faut s'inscrire"]),
                       ('h', "Faites-la fonctionner en deux formats"),
                       ('p', "Le même message demande souvent une grande affiche pour un mur et une image carrée pour les réseaux sociaux. Demandez les deux pour que les gens la voient partout."),
                       ('p', "Lisez-la une fois de l'autre bout de la pièce. Si vous ne distinguez pas de quel événement il s'agit, elle doit être plus simple.")])),
]


def FR_PAIRS():
    """English -> French strings for every translatable piece of the new posts."""
    out = {}
    for m in MORE:
        e, f = m['en'], m['fr']
        out[e['title']] = f['title']
        out[e['excerpt']] = f['excerpt']
        for (k1, v1), (k2, v2) in zip(e['body'], f['body']):
            assert k1 == k2, (m['slug'], k1, k2)
            if k1 == 'ul':
                assert len(v1) == len(v2), m['slug']
                out.update(dict(zip(v1, v2)))
            else:
                out[v1] = v2
    return out
