# Copy for the individual service pages (/services/<id>/). No client names, results or statistics are claimed.
# title/desc = search title and description (the brand name is added to the title); h1 may contain <span class="grad">
LANDING = {
    'brand': dict(
        slug='logo-design', title='Logo design and brand identity', desc="Logo design, brand identity and brand guidelines for new businesses, organizations and personal brands.",
        h1='A logo and a look that feels like <span class="grad">a real brand</span>',
        lead="Starting something, or giving it a fresh start? We design the logo, then the colours, lettering and rules that make everything you make look like it belongs together.",
        who=["New businesses that need a clean mark to begin with", "Established companies that want to look the part again", "Individuals building a personal brand"],
        get=["A logo designed around your idea and your audience", "Colours and fonts that work together", "Files for print and screen", "Brand guidelines you can hand to anyone who works with you"],
        faq=[("What's the difference between a logo and a brand identity?", "A logo is the mark that identifies you. A brand identity adds the colours, lettering and rules for using them, so everything you make looks consistent."),
             ("Can you refresh my existing logo?", "Yes. We can sharpen what you have or start over, whichever fits your goals."),
             ("What do you need from me to start?", "Your name, a few lines about what you do and who it's for, and any logos or colours you like or dislike. A few words is plenty.")]),
    'design': dict(
        slug='flyer-design', title='Flyer, poster and invitation design', desc="Flyers, posters, invitations, brochures and event graphics, ready for print or screen.",
        h1='Need a flyer? <span class="grad">We\'ve got you.</span>',
        lead="One flyer, one poster, one invitation is a real job and we're glad to do it. We design it so people notice it, read it and know what to do next.",
        who=["Events, openings and special offers", "Churches, ministries and community groups", "Businesses that need a menu, brochure or certificate"],
        get=["A design built around one clear message", "The right size and shape for where it will be used", "Print-ready and screen-ready files", "Two rounds of changes"],
        faq=[("What do I need to send?", "The words that must appear (dates, address, phone, website), your logo if you have one, and any photos you want used."),
             ("Can you design it for print and for social media?", "Yes. Tell us where it will appear and we'll prepare the right files for each."),
             ("Do you print it too?", "We prepare print-ready files. Printing is done by a printer, and we're happy to point you to a good one.")]),
    'social': dict(
        slug='social-media-design', title='Social media graphics', desc="Social media posts, campaign graphics, thumbnails and templates that look like they belong together.",
        h1='Posts people <span class="grad">actually stop for</span>',
        lead="One post or a whole month of them. We make graphics that look like they belong together, so your page looks like a proper brand.",
        who=["Businesses that post regularly and want a consistent look", "Campaigns, launches and events", "Creators and organizations growing an audience"],
        get=["Posts, stories and covers sized for each platform", "A consistent look across everything you publish", "Templates you can reuse so you only change the words and the photo", "Files ready to upload"],
        faq=[("Can you make templates I can edit myself?", "Yes. If you post often, ask for a set of templates for announcements, quotes, offers and events."),
             ("Which platforms do you design for?", "Instagram, Facebook, LinkedIn, YouTube and more. Tell us where you post."),
             ("Do you manage my accounts?", "No. We design the graphics. You or your team publish them.")]),
    'website': dict(
        slug='website-design', title='Website and landing page design', desc="Website and landing page design that people can actually understand, built to work well on phones.",
        h1='A website people can <span class="grad">actually understand</span>',
        lead="We design pages that explain what you do in the first scroll and make the next step obvious, and we build them to work on phones as well as computers.",
        who=["Businesses and organizations that need a clear online home", "People launching a product or an event", "Personal brands and portfolios"],
        get=["Page design with a clear structure", "A layout for your words and images", "A contact form that reaches you", "Files ready to publish"],
        faq=[("How many pages can I have?", "As many as you need. A simple landing page or a full website are both fine. We'll agree the pages in your quote."),
             ("Will it work on phones?", "Yes. We design and build every page to work well on a phone."),
             ("Can you write the text for it?", "We lay out your words. If you need help clarifying them, tell us and we'll talk about it.")]),
    'ads': dict(
        slug='billboard-and-banner-design', title='Billboard, banner and signage design', desc="Billboard, banner, roll-up and shop signage design that reads from across the road.",
        h1='Big, bold and <span class="grad">hard to miss</span>',
        lead="Billboards, banners, signs and backdrops have a few seconds to get noticed. We design them to be read from far away and remembered.",
        who=["Shops, offices and venues that need a sign", "Events that need banners and backdrops", "Campaigns that need outdoor advertising"],
        get=["Artwork made to the size and shape of your sign or banner", "A short, strong message that can be read from a distance", "Print-ready files", "Help finding the right printer or installer"],
        faq=[("Do you print and install it?", "We design the artwork to your supplier's sizes and specifications. Printing and installation are done by a printer or installer."),
             ("What do you need to know?", "The exact size, where it will be placed, and the message that must be read."),
             ("Can you make it match my brand?", "Yes. Send us your logo and colours, or ask us to design them first.")]),
    'vehicle': dict(
        slug='vehicle-branding', title='Vehicle branding and wraps', desc="Vehicle branding and wrap design for cars, vans and delivery vehicles.",
        h1='Your vehicle is already moving around the city. <span class="grad">Make it work for you.</span>',
        lead="A branded vehicle is advertising that goes to your customers. We design wraps for cars, vans and delivery vehicles that people notice and remember.",
        who=["Delivery and service businesses", "Companies with a fleet", "Anyone who wants their car or van to carry their brand"],
        get=["Artwork designed for the shape of your vehicle", "A clear message and contact details that can be read at a glance", "Print-ready files for your installer", "Help finding the right wrap installer"],
        faq=[("Do you install the wrap?", "We design the artwork and prepare the files. Installation is done by a wrap installer, and we can point you to one."),
             ("What do you need from me?", "The make and model of the vehicle (or a template from your installer), your logo, and the message and contact details to show."),
             ("Can one design work for several vehicles?", "Yes. We can adapt one design across a fleet.")]),
    'docs': dict(
        slug='presentation-design', title='Presentation and document design', desc="Pitch decks, presentations, proposals, reports and company profiles that look important.",
        h1='Make the important papers <span class="grad">look important</span>',
        lead="Pitch decks, proposals, reports and company profiles are read, signed and presented from. We make them clear, tidy and good-looking.",
        who=["Founders preparing a pitch", "Teams sending proposals and reports", "Professionals who need a CV or portfolio that stands out"],
        get=["A clean layout for your content", "Consistent colours and fonts across the whole document", "Editable files if you need to update them", "Print and screen versions"],
        faq=[("Can you work from my existing slides?", "Yes. Send what you have and we'll redesign it."),
             ("Will I be able to edit it afterwards?", "If you want editable files, we agree that in the quote."),
             ("Do you write the content?", "We design it. If your content needs work, tell us and we'll talk through options.")]),
    'packaging': dict(
        slug='packaging-design', title='Packaging and label design', desc="Packaging, label and book cover design that gets picked up.",
        h1='Something people <span class="grad">want to pick up</span>',
        lead="On a crowded shelf you have a second or two. We design pouches, boxes, labels and book covers so your product stands out and feels right.",
        who=["Food and product brands", "Businesses launching a new product", "Authors and publishers"],
        get=["A design made for the real shape of your packaging", "Clear brand name and product information", "Mockups so you can see it before it's made", "Print-ready files for your printer"],
        faq=[("Do you make the packaging?", "We design the artwork and prepare print-ready files. The packaging itself is made by a printer or manufacturer."),
             ("What do you need from me?", "The packaging type and dimensions (or your printer's template), your logo, and any text that must appear."),
             ("Can you design a book cover?", "Yes. Book covers are one of the things we design.")]),
    'media': dict(
        slug='photo-and-video-editing', title='Photo and video editing', desc="Photo retouching, video editing and short promotional videos and motion graphics.",
        h1='Make it look right <span class="grad">on screen</span>',
        lead="Photos that need a clean-up, videos that need cutting together, or a short animated piece to launch something. We make them look right.",
        who=["Businesses with photos that need retouching", "Campaigns that need a short promotional video", "Anyone launching something who wants it in motion"],
        get=["Retouching and image enhancement", "Video cut together and tidied", "Short promotional videos and motion graphics", "Files for the platform you'll use"],
        faq=[("What can you do with my photos?", "Clean-ups, retouching and enhancement so they look their best."),
             ("Can you make a short promo video?", "Yes. Tell us what it's for and where it will be shown."),
             ("Do you shoot photos or video?", "We edit and design with what you give us. Tell us if you need something else and we'll talk about it.")]),
}
