# Legal pages: a plain-language starting draft written to be fair to both the studio and its clients.
# EDIT the figures and wording that apply to you (marked in the README) and have a lawyer review before relying on it.
# blocks: ('h', text) heading · ('p', text) paragraph · ('ul', [items]) list
UPDATED = 'October 6, 2026'

PAGES = [
    dict(slug='privacy', title='Privacy Policy', short='Privacy Policy',
         intro="This explains what personal information ROVARD STUDIOS collects when you use this website or contact us, why we collect it, and the choices you have. We keep it short and plain on purpose.",
         body=[
             ('h', 'What we collect'),
             ('p', "We only collect what you choose to send us. When you fill in the Start a project form or email us, that can include:"),
             ('ul', ["Your name and, if you give it, your business name", "Your email address and, optionally, your phone or WhatsApp number", "What you need, a description of your idea, an optional budget range and an optional deadline", "Any files or links you send us"]),
             ('p', "We do not run advertising trackers, and we do not use analytics cookies on this website (see our Cookie Preferences page)."),
             ('h', 'How we use it'),
             ('ul', ["To reply to you and talk about your project", "To prepare quotes and deliver the work you ask for", "To send invoices and keep the records the law requires", "To keep our site and our systems secure"]),
             ('p', "We only email you about your enquiry or project. We won't add you to a newsletter unless you ask us to."),
             ('h', 'Who handles your information'),
             ('p', "Our contact form is processed by Formspree, which receives what you type and passes it to us by email. Our website is hosted by GitHub Pages, which, like most hosts, may record technical details such as your IP address in its server logs. These providers handle data under their own privacy terms and may store it outside Canada. We do not sell your information or rent it to anyone."),
             ('p', "We may also share information when the law requires it, or with professionals who help us run the studio (for example an accountant), who must keep it confidential."),
             ('h', 'Your work and your materials'),
             ('p', "Files, text and images you send us for a project stay yours. We use them only to do the work. Unless we have agreed otherwise in writing, we keep a copy of the finished work and the source files so that we can support you later."),
             ('h', 'How long we keep it'),
             ('p', "We keep enquiries and project records for as long as they are useful to you and us, and for as long as the law requires for accounting purposes. If you would like us to delete your information sooner, tell us and we will, unless we are legally required to keep it."),
             ('h', 'Your choices and rights'),
             ('p', "You can ask us to show you the personal information we hold about you, correct it, or delete it. If you are in a region with stronger privacy laws, such as Canada or the European Union, you may have additional rights, and we will respect them. To make a request, email hello@rovardstudios.com. If you are not happy with our answer, you may also contact your local privacy regulator."),
             ('h', 'Security'),
             ('p', "We take reasonable steps to protect your information, but no website or email is completely secure. Please don't send passwords, card numbers or other highly sensitive details through the contact form."),
             ('h', 'Children'),
             ('p', "This website is meant for adults and businesses. We do not knowingly collect information from children."),
             ('h', 'Changes to this policy'),
             ('p', "If we change how we handle information, we will update this page and the date at the top."),
             ('h', 'Contact'),
             ('p', "Questions about privacy? Email hello@rovardstudios.com."),
         ]),
    dict(slug='cookies', title='Cookie Preferences', short='Cookie Preferences',
         intro="Short version: this website does not use advertising or analytics cookies, so there is nothing for you to switch off.",
         body=[
             ('h', 'What cookies are'),
             ('p', "Cookies are small files a website can save in your browser. They are often used to remember you, count visitors or show ads."),
             ('h', 'What this website does'),
             ('ul', ["It does not set advertising or tracking cookies", "It does not use analytics tools that follow you around the web", "It does not need a cookie to work, so there is no banner to accept"]),
             ('p', "Our hosting provider and our contact form provider (Formspree) may process technical information such as your IP address when you load the site or send a message. That is described in our Privacy Policy."),
             ('h', 'Content from other sites'),
             ('p', "If we link to or embed something from another site (for example a video or a social profile), that site may set its own cookies when you use it. We do not control those, so please check their policies."),
             ('h', 'Your control'),
             ('p', "You can always block or delete cookies in your browser settings. If we ever add analytics or other optional cookies, we will ask for your permission first and add the controls to this page."),
             ('h', 'Questions'),
             ('p', "Email hello@rovardstudios.com."),
         ]),
    dict(slug='terms', title='Terms', short='Terms',
         intro="These terms cover how we work together and how you may use this website. They are written to be fair to both sides. If we agree something different in a written quote or contract for your project, that agreement comes first.",
         body=[
             ('h', 'Who we are'),
             ('p', "ROVARD STUDIOS (\"we\", \"us\") is a design studio based in Canada that works with clients around the world. \"You\" means the person or organization asking us to do the work."),
             ('h', '1. Quotes and getting started'),
             ('ul', ["We send a written quote that describes what we will make, the price, and the timeline", "The quote is valid for 30 days unless it says otherwise", "Work begins when you accept the quote and pay the deposit"]),
             ('h', '2. What you can expect from us'),
             ('ul', ["Careful, original work, made by us and the people we work with", "Clear updates, and a chance to shape the work along the way", "Respect for your deadlines and for your confidential information"]),
             ('h', '3. What we need from you'),
             ('ul', ["Clear information and materials (text, logos, photos) when we ask for them", "Feedback and approvals within a reasonable time, normally within 5 working days", "The right to use everything you give us. You promise that your text, images, names and logos don't infringe anyone else's rights"]),
             ('p', "If you are late with feedback or materials, the timeline moves back by the same amount."),
             ('h', '4. Revisions'),
             ('p', "Your price includes two rounds of changes to each deliverable, unless the quote says otherwise. A round means one set of consolidated feedback. Changes beyond that, or a change of direction after you have approved a stage, can be quoted separately."),
             ('h', '5. Payment'),
             ('ul', ["Unless the quote says otherwise, a 50% deposit is due before we start, and the balance is due when we deliver the final files", "Invoices are due within 14 days", "Deposits are non-refundable once work has started, because we set that time aside for you", "Late payments can pause the work. We may charge reasonable interest on overdue invoices", "Prices are shown without taxes, which are added where required"]),
             ('h', '6. Ownership of the work'),
             ('ul', ["When you have paid in full, you own the final approved work we deliver to you and may use it for your business", "Until payment is complete, we keep ownership and you may not use the work publicly", "We keep ownership of our working files, rough ideas, unused concepts and general know-how, unless the quote says the source files are included", "Fonts, stock images, plugins and other third-party material have their own licences. We will tell you when you need to buy or renew one"]),
             ('h', '7. Showing our work'),
             ('p', "We may show the finished work in our portfolio and on social media as an example of what we do. If you need it kept private, tell us before we start, and we will respect that. We will not publish your confidential information."),
             ('h', '8. Confidentiality'),
             ('p', "We each keep the other's non-public information private and use it only for the project."),
             ('h', '9. Changes and cancellation'),
             ('p', "Either of us can end the project in writing. If you cancel, you pay for the work done up to that point and for any costs we have already incurred. If we cancel, we refund any part of your deposit that doesn't cover work already done. Delivered work is yours once the amount due for it has been paid."),
             ('h', '10. Printing, production and third parties'),
             ('p', "Where we help arrange printing, signage, vehicle wraps or other production, that is a separate cost. We design the artwork to the specifications you or the supplier give us, and we are not responsible for a supplier's delays or errors, but we will help you resolve them. Colours can look different on screen and in print."),
             ('h', '11. Results'),
             ('p', "We work hard to make your project look right, but we can't promise particular business results such as sales, followers or rankings, because those depend on many things outside our control."),
             ('h', '12. Liability'),
             ('p', "To the extent the law allows, our total responsibility to you for anything related to a project is limited to the amount you paid us for that project, and we are not liable for indirect or lost-profit losses. Nothing in these terms limits liability that the law does not allow to be limited."),
             ('h', '13. This website'),
             ('p', "You may browse and share links to this website. The designs, images and text on it belong to us or to the clients and brands shown, and may not be copied or reused without permission. Some projects shown here are self-initiated studio work. We try to keep the site accurate and up to date but provide it as is."),
             ('h', '14. Governing law and disputes'),
             ('p', "These terms are governed by the laws that apply in the Canadian province where we are based. If something goes wrong, please talk to us first. Most problems are solved with a short conversation. If we can't resolve it, we will try mediation before going to court."),
             ('h', '15. Changes to these terms'),
             ('p', "We may update these terms. The version on this page when we accept your quote is the one that applies to your project."),
             ('h', 'Contact'),
             ('p', "Questions? Email hello@rovardstudios.com."),
         ]),
]
